---
# Poggit-Delta
#
# Copyright (C) 2018-2019 Poggit
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

sudo: required
language: node_js
env:
  global:
    - secure: "hz0z+H8ldFMiHi4gHjc05TM023ebVv2/nAVNwnbqtb//SpFTPItKwhLdX1owFALq+wVUwOlEAnFRmelYD76mEo7C8VvG4PFUUK1ur9lp8yXaXUJesKGbHIhMg7iWj3HEuiHt9MC79wcL2ITdufElZEPKc/v9ZY7bC4i8G3ryeCU4nbXdXRzwGkBgXN1KNaRlzxO13zlxxMqpvplbmyFIUjvP5rJYPZA8UZ87/VOut0ULryVZ3pmszmIKRR6iTemjXIRHw9LDiTFN3nAKXepaNabaGl99frtG8m5DHg35Zact3srzO/9l+ukd0ef/oITKLk2rS0eFtZKXeYhoEQgmqWi5A1GugGnaeOMZpEaNnLzmm83SfSRmu8TW6/hyJwVf2vyRe3Bt4UtOLJSBOWx3WyEcQY1olmiYnuLt36m6UABzwHdbLKNCgKlF9jeWOm9b4NfEcz3Sop8f6lW4sOAWQ0QHrurkFE26wlBprZt8H4SxNVrh+Uzqzj4Gc6I0hlGHt6G+1PUxGpojrzwuToLwZvxqnihIZqjgSWugBJDdgGPlwNiCBzkCkX2pQRkg8bGLHkxGsti448OYfvPyWzvRc8Ocqy6+KsIX9h/eJ8OKvszsDKnaWM4hEpG8N7sIPYcF8jl5Ta3BdUGqkbZbpx0DoNtremjEPeI/CvBHWDxSM4s="
services:
  - docker
node_js:
  - 8.14.0
before_install:
  - sudo apt-get update
  - sudo apt-get install -y jq
install:
  - npm install -g typescript ts-node yaml2json
before_script:
  - head -c16 /dev/urandom | base64 > mysql-password
  - touch output.log .server_started
  - docker run -v `pwd`/default-docker-compose.yml:/input sofe1970/yaml2json yaml2json /input
        | jq ".services.mysql.environment.MYSQL_PASSWORD = \"$(cat mysql-password)\""
        | jq ".services.mysql.environment.MYSQL_ROOT_PASSWORD = \"$(cat mysql-password)\""
        | jq ".services.app.environment.PGD_DEBUG = \"true\""
        | jq ".services.mysql.restart = \"no\""
        | jq ".services.app.restart = \"no\""
        > docker-compose.yml
  - mkdir secrets && cp travis/secrets-import.js secrets/secrets.js
  - cat travis/secrets-default.json
        | jq ".database.password = \"$(cat mysql-password)\""
        > secrets/secrets.json
  - docker-compose build
script:
  - ./travis/testUnit.sh
  - docker-compose up
  - while [ ! -f .server_started ]; do sleep 1; done
  - ./travis/testIntegration.sh
  - docker-compose down
...
